name: PR

on:
  pull_request:
    branches: [ master ]
jobs:
  check-package-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn global add semver-compare-cli
      - run: export PATH="$PATH:$(yarn global bin)"
      - name: Get local package version
        run: echo "::set-output name=CURRENT_PACKAGE_VERISION::$(node -p 'require(`./package.json`).version')"
        id: current-package-version
      - name: Get remote package version
        run: echo "::set-output name=REMOTE_PACKAGE_VERISION::$(npm view @1inch/calldata-compressor version)"
        id: remote-package-version
      - name: Check Version
        run: semver-compare ${{ steps.current-package-version.outputs.CURRENT_PACKAGE_VERISION }} gt ${{ steps.remote-package-version.outputs.REMOTE_PACKAGE_VERISION }}
